##############################
#    Quantum Time Config    #
##############################

# Appearance configuration.
# If you want to change how Medusa looks, you can do it here.
appearance:

  # Theme system.
  # How to make theme:
  # Split the string with dollar sign symbol ($)
  # First, put the name of the Theme (Ex: Medusa)
  # Then, put $ and space after it (Ex: Medusa$ )
  #
  # After this, put the alert format and a $ after it,
  # followed by a space (Ex: &aMedusa » &f%player% &7failed &f%checkName% &7(x%vl%)$ )
  #
  # Then, put TWO (no more, no less, can be the same)
  # accent colours you want using the Minecraft colour code symbols (Ex: &a &c)
  #
  # Placeholders:
  # %player% - Player's name
  # %uuid% - Player's UUID
  # %checkName% - Name of the check (e.g. Reach, AutoClicker, KillAura, Speed, Fly)
  # %checkType% - ID of the check, just a letter like A, B, C.
  # %dev% - Experimental status of the check, if the check has a "*" after it, it's experimental.
  # %vl% - Current violation level of the check flagged.
  # %maxvl% - Maximum violation level of the check flagged.
  # %ping% - Latency of the player.
  # %tps% - TPS of the server.

  themes:
    Medusa:
      message: 'Medusa » &f%player% &7failed &f%checkName% (%checkType%) &7(x%vl%) &c%dev%'
      colors:
        - '&a'
        - '&2'
    Overflow:
      message: '&7[&cMedusa&7] %player% flagged &c%checkName% (type %checkType%) VL: &c%vl% %dev%'
      colors:
        - '&c'
        - '&4'
    sturkvturk:
      message: |
        &3&l[&b&lQ&f&lT&b&lA&3&lC&3&l] &f%player% &7failed &b%checkName%&3(&f%checkType%&3) &f%dev%
        &8[&b&l!&8] &7VL: &f%vl%&7/&f%maxvl% &8| &7Ping: &f%ping%ms &8| &7TPS: &f%tps%
      colors:
        - '&b'
        - '&b'
    svzold:
      message: |
        &2&l[&a&lQ&e&lT&a&lA&2&lC&2&l] &f%player% &7failed &a%checkName%&2(&e%checkType%&2) &e%dev%
        &8[&a&l!&8] &7VL: &f%vl%&7/&f%maxvl% &8| &7Ping: &f%ping%ms &8| &7TPS: &f%tps%
      colors:
        - '&a'
        - '&2'
    szfeher:
      message: |
        &8&l[&f&lQ&7&lT&f&lA&8&lC&8&l] &f%player% &7failed &f%checkName%&8(&7%checkType%&8) &7%dev%
        &8[&f&l!&8] &7VL: &f%vl%&7/&f%maxvl% &8| &7Ping: &f%ping%ms &8| &7TPS: &f%tps%
      colors:
        - '&f'
        - '&8'
    svkek:
      message: |
        &1&l[&9&lQ&b&lT&9&lA&1&lC&1&l] &f%player% &7failed &9%checkName%&1(&b%checkType%&1) &b%dev%
        &8[&9&l!&8] &7VL: &f%vl%&7/&f%maxvl% &8| &7Ping: &f%ping%ms &8| &7TPS: &f%tps%
      colors:
        - '&9'
        - '&1'
    pirarany:
      message: |
        &4&l[&c&lQ&6&lT&c&lA&4&lC&4&l] &f%player% &7failed &c%checkName%&4(&6%checkType%&4) &6%dev%
        &8[&c&l!&8] &7VL: &f%vl%&7/&f%maxvl% &8| &7Ping: &f%ping%ms &8| &7TPS: &f%tps%
      colors:
        - '&c'
        - '&4'
    narsarg:
      message: |
        &6&l[&e&lQ&c&lT&e&lA&6&lC&6&l] &f%player% &7failed &e%checkName%&6(&c%checkType%&6) &c%dev%
        &8[&e&l!&8] &7VL: &f%vl%&7/&f%maxvl% &8| &7Ping: &f%ping%ms &8| &7TPS: &f%tps%
      colors:
        - '&e'
        - '&6'
    lilrozs:
      message: |
        &5&l[&d&lQ&e&lT&d&lA&5&lC&5&l] &f%player% &7failed &d%checkName%&5(&e%checkType%&5) &e%dev%
        &8[&d&l!&8] &7VL: &f%vl%&7/&f%maxvl% &8| &7Ping: &f%ping%ms &8| &7TPS: &f%tps%
      colors:
        - '&d'
        - '&5'
    kekaqua:
      message: |
        &1&l[&b&lQ&3&lT&b&lA&1&lC&1&l] &f%player% &7failed &b%checkName%&1(&3%checkType%&1) &3%dev%
        &8[&b&l!&8] &7VL: &f%vl%&7/&f%maxvl% &8| &7Ping: &f%ping%ms &8| &7TPS: &f%tps%
      colors:
        - '&7'
        - '&b'


  # Accent colours. Changes color look of aspects of Medusa.
  accents:
    accentOne: '&c'
    accentTwo: '&4'

# Violation configuration section.
# Placeholders:
# %player% - Player's name
# %uuid% - Player's UUID
# %checkName% - Name of the check (e.g. Reach, AutoClicker, KillAura, Speed, Fly)
# %checkType% - ID of the check, just a letter like A, B, C.
# %dev% - Experimental status of the check, if the check has a "*" after it, it's experimental.
# %vl% - Current violation level of the check flagged.
# %maxvl% - Maximum violation level of the check flagged.
# %ping% - Latency of the player.
# %tps% - TPS of the server.
# (VL = Violation Level = How many times a player has flagged the check)
violations:
  alert-format: |
    &4&l[&c&lQ&6&lT&c&lA&4&lC&4&l] &f%player% &7failed &c%checkName%&4(&6%checkType%&4) &6%dev%
    &8[&c&l!&8] &7VL: &f%vl%&7/&f%maxvl% &8| &7Ping: &f%ping%ms &8| &7TPS: &f%tps%
  alert-cooldown: 0
  minimum-vl-to-alert: 1
  clear-violations-delay: 5

checks:
  combat:
    aimassist:
      a:
        enabled: true
        max-violations: 20
        punish-command: ''
      b:
        enabled: true
        max-violations: 18
        punish-command: ''
      c:
        enabled: true
        max-violations: 22
        punish-command: ''
      d:
        enabled: true
        max-violations: 25
        punish-command: ''
      e:
        enabled: true
        max-violations: 19
        punish-command: ''
      f:
        enabled: true
        max-violations: 23
        punish-command: ''
      g:
        enabled: true
        max-violations: 27
        punish-command: ''
      h:
        enabled: true
        max-violations: 26
        punish-command: ''
      i:
        enabled: true
        max-violations: 28
        punish-command: ''
    autoclicker:
      a:
        enabled: true
        max-violations: 24
        punish-command: ''
        max-cps: 24
      b:
        enabled: true
        max-violations: 21
        punish-command: ''
      c:
        enabled: true
        max-violations: 23
        punish-command: ''
      d:
        enabled: true
        max-violations: 26
        punish-command: ''
      e:
        enabled: true
        max-violations: 22
        punish-command: ''
    hitbox:
      a:
        enabled: true
        max-violations: 25
        punish-command: ''
        raytrace-sensitivity-level: 2
        max-latency: -1
        setback: true
      b:
        enabled: true
        max-violations: 27
        punish-command: ''
        setback: true
    killaura:
      a:
        enabled: true
        max-violations: 20
        punish-command: ''
        setback: true
      b:
        enabled: true
        max-violations: 22
        punish-command: ''
        setback: true
      c:
        enabled: true
        max-violations: 24
        punish-command: ''
        setback: true
      d:
        enabled: true
        max-violations: 26
        punish-command: ''
        setback: true
      e:
        enabled: true
        max-violations: 28
        punish-command: ''
        setback: true
      f:
        enabled: true
        max-violations: 30
        punish-command: ''
        setback: true
      g:
        enabled: true
        max-violations: 29
        punish-command: ''
        setback: true
    reach:
      a:
        enabled: false
        max-violations: 25
        punish-command: ''
        max-reach: 3.0
        max-threshold: 3.0
        threshold-decay: 0.1
        max-latency: -1
        setback: true
      b:
        enabled: false
        max-violations: 27
        punish-command: ''
        max-latency: -1
        setback: true
      c:
        enabled: true
        max-violations: 26
        punish-command: ''
        max-reachDev: 3.0
        max-latencyDev: -1
        setback: true
    velocity:
      a:
        enabled: true
        max-violations: 23
        punish-command: ''
        minimum-velocity-percentage: 100
        maximum-velocity-percentage: 100
        setback: true
      b:
        enabled: true
        max-violations: 25
        punish-command: ''
        setback: true
  movement:
    fastclimb:
      a:
        enabled: true
        max-violations: 20
        punish-command: ''
        setback: true
    fly:
      a:
        enabled: true
        max-violations: 28
        punish-command: ''
        setback: true
      b:
        enabled: true
        max-violations: 26
        punish-command: ''
        setback: true
      c:
        enabled: true
        max-violations: 24
        punish-command: ''
        setback: true
      d:
        enabled: true
        max-violations: 22
        punish-command: ''
        setback: true
    selfdamage:
      a:
        enabled: true
        max-violations: 30
        punish-command: ''
        setback: true
    jesus:
      a:
        enabled: true
        max-violations: 25
        punish-command: ''
        setback: true
      b:
        enabled: true
        max-violations: 27
        punish-command: ''
        setback: true
    motion:
      a:
        enabled: true
        max-violations: 21
        punish-command: ''
        setback: true
      b:
        enabled: true
        max-violations: 23
        punish-command: ''
        setback: true
      c:
        enabled: true
        max-violations: 25
        punish-command: ''
        setback: true
      d:
        enabled: true
        max-violations: 27
        punish-command: ''
        setback: true
      e:
        enabled: true
        max-violations: 29
        punish-command: ''
        setback: true
    noslow:
      a:
        enabled: true
        max-violations: 26
        punish-command: ''
        setback: true
    phase:
      a:
        enabled: false
        max-violations: 28
        punish-command: ''
        setback: true
    speed:
      a:
        enabled: true
        max-violations: 25
        punish-command: ''
        setback: true
      b:
        enabled: true
        max-violations: 27
        punish-command: ''
        setback: true
      c:
        enabled: true
        max-violations: 23
        punish-command: ''
      d:
        enabled: true
        max-violations: 23
        punish-command: ''
    strafe:
      a:
        enabled: true
        max-violations: 26
        punish-command: ''
  player:
    hand:
      a:
        enabled: true
        max-violations: 22
        punish-command: ''
    inventory:
      a:
        enabled: true
        max-violations: 24
        punish-command: ''
        setback: true
      b:
        enabled: true
        max-violations: 26
        punish-command: ''
        setback: true
    protocol:
      a:
        enabled: true
        max-violations: 15
        punish-command: ''
      b:
        enabled: true
        max-violations: 17
        punish-command: ''
      c:
        enabled: true
        max-violations: 19
        punish-command: ''
      d:
        enabled: true
        max-violations: 21
        punish-command: ''
      e:
        enabled: true
        max-violations: 23
        punish-command: ''
      f:
        enabled: true
        max-violations: 25
        punish-command: ''
      g:
        enabled: true
        max-violations: 27
        punish-command: ''
      h:
        enabled: true
        max-violations: 29
        punish-command: ''
      i:
        enabled: true
        max-violations: 30
        punish-command: ''
      j:
        enabled: true
        max-violations: 28
        punish-command: ''
      k:
        enabled: true
        max-violations: 26
        punish-command: ''
      l:
        enabled: true
        max-violations: 26
        punish-command: ''
        setback: true
      x:
          enabled: true
          max-violations: 26
          punish-command: ''
      z:
          enabled: true
          max-violations: 26
          punish-command: ''
    scaffold:
      a:
        enabled: true
        max-violations: 22
        punish-command: ''
        setback: true
      b:
        enabled: true
        max-violations: 24
        punish-command: ''
        setback: true
      c:
        enabled: true
        max-violations: 26
        punish-command: ''
        setback: true
      d:
        enabled: true
        max-violations: 28
        punish-command: ''
        setback: true
    timer:
      a:
        enabled: true
        max-violations: 25
        punish-command: ''
        max-timer-speed: 1.02
        setback: true
      b:
        enabled: true
        max-violations: 27
        punish-command: ''
        minimum-timer-speed: 0.75
        setback: true
      c:
        enabled: true
        max-violations: 29
        punish-command: ''
        maximum-balance: 0
        balance-reset: -50
        balance-subtraction-on-teleport: 50
        setback: true