name: QuantumTimeAntiCheat

version: 1.5.3
main: com.gladurbad.medusa.MedusaPlugin
authors: [GladUrBad]
description: Quantum Time AntiCheat

commands:
  qtac:
    description: Commands for Quantum Time AntiCheat.
    usage: /qtac
    aliases: [anticheat, ac]
    permission: medusa.commands


